spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
        use_sql_comments: false
        cache:
          use_second_level_cache: false
          use_query_cache: false
  
  flyway:
    enabled: false
  
  cache:
    type: simple

logging:
  level:
    io.conduktor.saas: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.testcontainers: INFO
    root: INFO

app:
  jwt:
    secret: testSecretKey123456789012345678901234567890123456789012345678901234567890
    expiration: 3600000 # 1 hour for tests
  
  cors:
    allowed-origins: http://localhost:3000,http://localhost:3001,http://localhost:5173,http://localhost:8081,http://127.0.0.1:5173
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
    allowed-headers: "*"
    allow-credentials: true
    max-age: 3600